# List of universities that are definitely NOT in the US.
NUS_inst = [
    'Acad. of Sciences, Prague',
    'Academia Sinica Institute of Astronomy and Astrophysics',
    'ALMA',
    'Argelander Institute for Astronomy, University of Bonn',
    'Argelander Institut fur Astronomie/Humboldt Fellow',
    'ASIAA',
    'Astrobiology Center (INTA, CSIC) - Spain',
    'ASTRON',
    'Australia Telescope National Facility',
    'Bonn',
    'Bristol University',
    'Cambridge U.',
    'Cambridge Univ.',
    'Cavendish Laboratory, University of Cambridge',
    'CEA',
    'CEA Saclay',
    'CEA-Saclay',
    'CESR',
    'Chalmers University of Technology',
    'CITA',
    'CRyA-UNAM',
    'CSIRO',
    'Curtin',
    'Durham',
    'Durham University',
    'Dublin Institute for Advanced Studies',
    'Edinburgh',
    'ESA',
    'ESA/ESTEC',
    'ESO',
    'ESO/Manchester',
    'European Southern Observatory',
    'Faculty of Science, Hong Kong University',
    'Hebrew University',
    'Herzberg Institute of Astrophysics',
    'Herzberg Institute of Astrophysics, Canada',
    'Hokkaido Univ.',
    'IA-UNAM',
    'IAA, Spain',
    'IAC',
    'IAP',
    'Ibaraki University',
    'ICATE, Universidade de Sao Paulo',
    'ICE (IEEC-CSIC)',
    'IFSI-INAF, Rome, Italy',
    'Imperial College',
    'INAF',
    'INAF-IASF',
    'INAF - Arcetri (Florence)',
    'INAF - Arcetri Observatory',
    'INAF - Osservatorio di Arcetri',
    'INAF - Osservatorio Astrofisico di Arcetri',
    'INAF-Osservatorio Astrofisico di Arcetri',
    'INAF - IAPS',
    'INAF - IFSI (Rome)',
    'INAF - IFSI',
    'INAF-IRA, Italy',
    'INAF-OAA, Italy',
    'INAF-Osservatorio Astrofisico di Arcetri',
    'INAOE',
    "Institut de Ciencies de l'Espai (CSIC)",
    'Institute of Physics, Vietnam',
    'Instituto de Astrofisica de Andalucia',
    "Institut d'Astrophysique de Paris, France",
    'INTA CSIC, Madrid',
    'IRAM',
    'ISAS/JAXA',
    'ITA, Uni Heidelberg',
    'JAXA',
    'Jodrell Bank Observatory',
    'Kapteyn Institute,Groningen',
    'Kapteyn Astronomical Inst.',
    'Keio University',
    'Kyoto University',
    'Laboratoire AIM, IRFU/SAp, CEA-Saclay, France',
    "Laboratoire d'Astrophysique de Bordeaux",
    "Laboratoire d'Astrophysique de Marseille",
    'Leiden',
    'Leiden Observatory',
    'Leiden Observatory, the Netherlands',
    'LERMA',
    'LERMA Paris',
    'LMU Munich',
    'Macquarie University',
    'Max Planck Institut fur Extraterrestrische Physik, Germany',
    'Max-Planck-Institut fuer Radioastronomie',
    'Max Planck Institute for Radioastronomy',
    'Max Planck Institute for Solar System Research',
    'Max Planck Institute for Solar System Research, Germany',
    'McGill',
    'McMaster University',
    'MPE',
    'MPE Garching',
    'MPI Garching',
    'MPIA',
    'MPIA, Heidelberg',
    'MPIA Heidelberg',
    'MPIfR',
    'MPirF',
    'MRAO',
    'NAOJ',
    'National Institute of Information and Communications Technology, Japan',
    'National Observatory, Rio de Janeiro',
    'National Observatory, Rio de Janeiro ', 
    'National Tsing Hua University',
    'NJU/SHAO',
    'Nobeyama Radio Observatory', 
    'Nobeyama Radio Observatory ',
    'Nottingham',
    'NRC-HIA',
    'NRO',
    'NRO/NAOJ',
    'OAN Madrid',
    'Obs. de Paris, France',
    "Observatoire de la Cote d'Azur",
    'Observatoire de la Cote d',
    'Observatorio Astronomico Nacional',
    'Observatorio Nacional, Brazil',
    'Open University',
    '1. Physikalisches Institut, Uni Koeln',
    'Pontificia Universidad Catolica de Chile',
    'Purple Mountain Observatory, CAS, China',
    'Royal Military College of Canada',
    'Sussex',
    'SRON, Groningen',
    'SRON \& Univ Groningen, the Netherlands',
    'St Petersburg Univ.',
    'Tel Aviv University',
    'Tianjin Astrophysics Center, Tianjin Normal University, China',
    'TIFR, India',
    'Tokyo Univ.',
    'Trinity College Dublin, Dublin',
    'U-PSUD',
    'UIO',
    'UBC',
    'UNAM',
    'Universidad Catolica de Chile',
    'Universidad Nacional Autonoma de Mexico',
    'Universidad Nacional Autonoma de Mexico,  Institute of Astronomy:Ensenada BC',
    'Universidade de Sao Paulo',
    'Univ. of Cologne - Germany',
    'Univ. of Leicester, UK',
    'Univ. of Sao Paulo',
    'Univ-Paris',
    'University of Bonn',
    'University of Bristol',
    'University of Cambridge',
    'The University of Cambridge',
    'University of Chile',
    'University of Erlangen-Nuremberg',
    'University of KwaZulu-Natal',
    'University of Leeds',
    'University of Leeds, United Kingdom',
    'University of Manchester',
    'University of Manitoba',
    ' University of Portsmouth',
    'University of Southampton',
    'University of Sydney',
    'University of Tokyo/NAOJ',
    'University of Tokyo',
    'The university of Tokyo',
    'University of Victoria',
    'University of Western Ontario, Caltech',
    'UKZN',
    'Vienna',
    'Weizmann Institute',
]

# List of universities that are definitely in the US.
US_inst = [ 
    'AFRL',
    'Arizona',
    'Boston University',
    'Cal State Los Angeles',
    'Caltech',
    'Caltech/JPL',
    'Caltech/OVRO',
    'Colorado',
    'Carnegie',
    'Carnegie Institution for Science',
    'Center for Astrophysics and Space Astronomy, University of Colorado',
    'Columbia University',
    'Cornell',
    'Cornell University',
    'CfA',
    'CfA/NJU',
    'Cfa Harvard',
    'CfA, Harvard University',
    'CfA, Harvard University - Peking University',
    'Emory University',
    'Georgia Institute of Technology',
    'Georgia Southern University',
    'Harvard',
    'Harvard ',
    'Harvard University',
    'Harvard-CfA',
    'Harvard-CFA',
    'Harvard-Smithsonian',
    'Harvard-Smithsonian CfA',
    'Harvard Smithsonian Center for Astrophysics (CfA)',
    'Havard-Smithsonian Center for Astrophysics',
    'Hawaii',
    'Hawaii IfA',
    'IfA Hawaii',
    "Institute for Astronomy, Hawai'i", 
    'IPAC',
    'Johns Hopkins',
    'Johns Hopkins University',
    'Johns Hopkins University ',
    'JPL',
    'JPL (NASA, Caltech)',
    'JPL, Caltech',
    'LBL',
    'Lawrence Berkeley Lab',
    'MIT Kavli Institute',
    'NASA GSFC',
    'NASA/GSFC',
    'NASA Goddard',
    'NASA Herschel Science Center',
    'NASA Herschel Science Center/Caltech',
    'New Mexico Tech',
    'NOAO USA',
    'Northwestern University',
    'NRAO',
    'NRAO, Charlottesville',
    'National Radio Astronomy Observatory',
    'National Radio Astronomy Observatory/University of Virginia',
    'NJIT',
    'OVRO',
    'Penn State',
    'Penn State University',
    'Princeton',
    'Princeton University',
    'Purdue University',
    'Rutgers',
    'Rutgers University',
    'SAO CfA/Taiwan University',
    'SAO CfA/ASIAA',
    'SAO CfA',
    'SETI',
    'SMA',
    'SOFIA/USRA',
    'Space Telescope Science Institute',
    'SSC',
    'Stanford',
    'Stanford University',
    'Stony Brook University',
    'Stony Brook Univ.',
    'Stony Brook Univ',
    'Texas A\&M',
    'UC Berkeley',
    'UC - Berkeley, MPE Garching',
    'UC Davis',
    'UC Irvine',
    'UC Santa Cruz',
    'U of Wisconsin',
    'UArizona',
    'UAH',
    'UChicago',
    'UCLA',
    'UFlorida',
    'UH IfA',
    'UIUC',
    'UMASS',
    'UMass',
    'UMD',
    'UMichigan Ann Arbor, Observatorio Nacional Brazil',
    'UMissouri-Kansas City',
    'University of Alabama, Huntsville',
    'University of Arizona',
    'University of Florida',
    'University of Hawaii',
    'University of Massachusetts',
    'University of Michigan',
    'University of Minnesota',
    'University of Pennsylvania',
    'University of Rochester',
    'University of Texas',
    'University of Toledo',
    'University of Virginia',
    'University of Wisconsin',
    'Univ. of Washington',
    'Univ. of Wisconsin Milwaukee',
    'UPenn',
    'USRA - SOFIA',
    'UT Austin',
    'UvA',
    'West Virginia University',
    'Williams College',
    'Yale',
]

def isus(inst):
    if inst in US_inst:
        return '1'
    elif inst in NUS_inst:
        return '0'
    else:
        print inst
        return 'N/A'

