# List of universities that are definitely NOT in the US.
NUS_inst = [
    'Acad. of Sciences, Prague',
    'Academia Sinica Institute of Astronomy and Astrophysics',
    'AIfA',
    'ALMA',
    'ALMA, Chile',
    'Arcetri Observatory',
    'Arcetri Astrophysical Observatory, INAF',
    'Argelander Institute for Astronomy, University of Bonn',
    'Argelander Institut fur Astronomie/Humboldt Fellow',
    'ASIAA',
    'ASIAA (Taiwan)',
    'Astrobiology Center (INTA, CSIC) - Spain',
    'Astro Space Center, P.N. Lebedev Physical Institute of the Russian Academy of Sciences',
    'Astro Space Center, P. N. Lebedev Physical Institute of the Russian Academy of Sciences ',
    'ASTRON',
    'Australia Telescope National Facility',
    'Australian Astronomical Observatory',
    'Barcelona',
    'Bonn',
    'Bristol University',
    'Calgary',
    'Cambridge U.',
    'Cambridge Univ.',
    'CAB (INTA/CSIC, Spain)',
    'CASS',
    'Cavendish Laboratory, University of Cambridge',
    'Cavendish laboratory, Cambridge',
    'CEA',
    'CEA Saclay',
    'CEA-Saclay',
    'CEA - Saclay',
    'Centro de Astrobiologia (CAB-INTA-CSIC. Madrid-Spain)',
    'CESR',
    r"""Centro de Radioastronom\'\i a y Astrof\'\i sica, Universidad Nacional Autonoma de M\'exico""",
    'Centro de Radioastronomia y Astrofisica, UNAM',
    'Chalmers University of Technology',
    'Charles Univ., Prague, Czech Rep.',
    'CITA',
    'Cologne',
    'CRyA-UNAM',
    'CSIRO',
    'Curtin',
    'Curtin University',
    'Dept. of Astronomy and Space Science, Kyung Hee University',
    'Durham',
    'Durham University',
    'Dublin Institute for Advanced Studies',
    'Edinburgh',
    'ESA',
    'ESA/ESTEC',
    'ESO',
    'ESO/Manchester',
    'ESO Garching',
    'ESO - Garching',
    'ESO \& University of Southampton',
    'ESO-Garching',
    'European Southern Observatory',
    'Faculty of Science, Hong Kong University',
    'Hebrew University',
    'Heidelberg',
    'Helsinki',
    'Hertfordshire',
    'Herzberg Institute of Astrophysics',
    'Herzberg Institute of Astrophysics, Canada',
    'HCMIU-Vietnam National University',
    'Hokkaido Univ.',
    'Hwa Chong Institution',
    'IA-UNAM',
    'IAA, Spain',
    'IAC',
    'IAP',
    'IAPS - INAF',
    'Ibaraki University',
    'ICATE, Universidade de Sao Paulo',
    'ICE (IEEC-CSIC)',
    'IFSI-INAF, Rome, Italy',
    'Imperial College',
    'INAF',
    'INAF-IASF',
    'INAF - Arcetri (Florence)',
    'INAF - Arcetri Observatory',
    'INAF - Osservatorio di Arcetri',
    'INAF - Osservatorio Astrofisico di Arcetri',
    'INAF-Osservatorio Astrofisico di Arcetri',
    'INAF - IAPS',
    'INAF - IFSI (Rome)',
    'INAF - IFSI',
    'INAF-IRA, Italy',
    'INAF-OAA, Italy',
    'INAF-Osservatorio Astrofisico di Arcetri',
    'INAOE',
    'Indian Institute of Astrophysics',
    "Institut de Ciencies de l'Espai (CSIC)",
    'Institute of Physics, Vietnam',
    'Institute of Space Sciences (CSIC/IEEC, Spain)',
    'Instituto de Astrofisica de Andalucia',
    "Institut d'Astrophysique de Paris, France",
    'Institute of Space Science',
    'INTA CSIC, Madrid',
    'IRAM',
    'ISAS/JAXA',
    'ITA, Uni Heidelberg',
    'JAXA',
    'Jodrell Bank Observatory',
    'Joint ALMA Obs. (Chile); ESO (Germany)',
    'Kapteyn Institute,Groningen',
    'Kapteyn Astronomical Inst.',
    'Kapteyn Astronomical Institute',
    'KASI',
    'Keio University',
    'Kyoto University',
    'Kyung Hee University',
    'Laboratoire AIM, IRFU/SAp, CEA-Saclay, France',
    "Laboratoire d'Astrophysique de Bordeaux",
    "Laboratoire d'Astrophysique de Marseille",
    'Leiden',
    'Leiden Observatory',
    'Leiden Observatory, the Netherlands',
    'Leiden University',
    'LERMA',
    'LERMA Paris',
    'LMU Munich',
    ' Ludwigs-Maximilians University, Munich',
    'Macquarie University',
    'Macalester',
    'Max Planck Institut fur Extraterrestrische Physik, Germany',
    'Max-Planck-Institut fuer Radioastronomie',
    'Max Planck Institute for Radioastronomy',
    'Max Planck Institut fur Astronomie',
    'Max Planck Institute for Solar System Research',
    'Max Planck Institute for Solar System Research, Germany',
    'Max-Planck-Institut fur Radioastronomie',
    'Max Planck Institute for Radio Astronomy',
    'McGill',
    'McMaster University',
    'MPE',
    'MPE Garching',
    'MPI Garching',
    'MPIA',
    'MPIA, Heidelberg',
    'MPIA Heidelberg',
    'MPIfR',
    'MPirF',
    'MRAO',
    'NAOJ',
    'National Institute of Information and Communications Technology, Japan',
    'National Observatory, Rio de Janeiro',
    'National Observatory, Rio de Janeiro ', 
    'National Research Council Canada',
    'National Research Council of Canada',
    'National Taiwan Normal University',
    'National Tsing Hua University',
    'National Tsing Hua U.',
    'NJU/SHAO',
    'Nobeyama Radio Observatory', 
    'Nobeyama Radio Observatory ',
    'Nottingham',
    'NRC-HIA',
    'NRO',
    'NRO/NAOJ',
    'OAMP',
    'OAN Madrid',
    'Obs. de Paris, France',
    "Observatoire de la Cote d'Azur",
    'Observatoire de la Cote d',
    'Observatorio Astronomico Nacional',
    'Observatorio Astronomico Nacional, Madrid, Spain.',
    'Observatoire Astronomique de Marseille Provence',
    'Observatorio Nacional, Brazil',
    'Onsala Space Observatory',
    'Open University',
    'Oxford',
    'Oxford University',
    '1. Physikalisches Institut, Uni Koeln',
    'Pontificia Universidad Catolica de Chile',
    'Pontificia Universidad Catolica de Chile (PUC)',
    'Purple Mountain Observatory, CAS, China',
    "Queen's University Belfast",
    'Royal Military College of Canada',
    'Royal observatory of Edinburgh',
    'Sussex',
    'SRON',
    'SRON, Groningen',
    'SRON \& Univ Groningen, the Netherlands',
    'St Petersburg Univ.',
    'Swinburne University of Technology',
    'Tel Aviv University',
    'Tianjin Astrophysics Center, Tianjin Normal University, China',
    'TIFR, India',
    'Tokyo Univ.',
    'Toronto',
    'Trinity College Dublin, Dublin',
    'U-PSUD',
    'UIO',
    'UBC',
    'UNAM',
    'Universidad Catolica de Chile',
    'Universidad Nacional Autonoma de Mexico',
    'Universidad Nacional Autonoma de Mexico,  Institute of Astronomy:Ensenada BC',
    'Universidade de Sao Paulo',
    'Universidad de Granada',
    'Universitat de Barcelona',
    'Univ. of Cologne - Germany',
    'Univ. of Leicester, UK',
    'Univ. of Sao Paulo',
    'Univ. of Sao Paulo, Brazil',
    'Univ-Paris',
    'University of Amsterdam',
    'University of Bonn',
    'University of Bristol',
    'University of Cambridge',
    'The University of Cambridge',
    'University of Cape Town',
    'University of Central Lancashire',
    'University of Chile',
    'University of Cologne',
    'University of Crete',
    'University of Erlangen-Nuremberg',
    'University of Erlangen-Nuremberg\t',
    'University of Exeter',
    'University of KwaZulu-Natal',
    'University of Leeds',
    'University of Leeds, United Kingdom',
    'University of Manchester',
    'University of Manitoba',
    ' University of Portsmouth',
    'University of Southampton',
    'University of Stockholm',
    'University of Sydney',
    'University of Tokyo/NAOJ',
    'University of Tokyo',
    'The university of Tokyo',
    'University of Victoria',
    'University of Western Ontario, Caltech',
    'Universitaets-Sternwarte Muenchen',
    'UKZN',
    'Vienna',
    'Weizmann Institute',
    '-',
]

# List of universities that are definitely in the US.
US_inst = [ 
    'AFRL',
    'Arizona',
    'Boston University',
    'Cal State Los Angeles',
    'Caltech',
    'Caltech/JPL',
    'Caltech/OVRO',
    'Center for Astrophysics and Space Astronomy, University of Colorado at Boulder',
    'Center for Astrophysics and Space Astronomy, University of colorado at Boulder',
    'Colorado',
    'Carnegie',
    'Carnegie Institution for Science',
    'Center for Astrophysics and Space Astronomy, University of Colorado',
    'Columbia University',
    'Cornell',
    'Cornell University',
    'CfA',
    'CfA/NJU',
    'CfA/SMA',
    'Cfa Harvard',
    'CfA, Harvard University',
    'CfA, Harvard University - Peking University',
    'Department of Astrophysical Sciences, Princeton',
    'Emory University',
    'George Washington University',
    'Georgia Institute of Technology',
    'Georgia Southern University',
    'Harvard',
    'Harvard ',
    'Harvard University',
    'Harvard-CfA',
    'Harvard-CFA',
    'Harvard-Smithsonian',
    'Harvard-Smithsonian CfA',
    'Harvard-Smithsonian CfA ',
    'Harvard Smithsonian Center for Astrophysics (CfA)',
    'Havard-Smithsonian Center for Astrophysics',
    'Hawaii',
    'Hawaii IfA',
    'IfA Hawaii',
    'Indiana',
    "Institute for Astronomy, Hawai'i", 
    'IAS',
    'IPAC',
    'IPAC/Caltech',
    'IPAC / Caltech',
    'Johns Hopkins',
    'Johns Hopkins University',
    'Johns Hopkins University ',
    'JPL',
    'JPL (NASA, Caltech)',
    'JPL, Caltech',
    'LBL',
    'Lawrence Berkeley Lab',
    'Michigan',
    'Michigan State University',
    'Minnesota',
    'MIT Haystack Observatory',
    'MIT Kavli Institute',
    'NASA Ames Research Center',
    'NASA Ames Research Center ',
    'NASA GSFC',
    'NASA/GSFC',
    'NASA-GSFC',
    'NASA Goddard',
    'NASA Goddard Space Flight Center',
    'NASA Herschel Science Center',
    'NASA Herschel Science Center/Caltech',
    'New Mexico Tech',
    'New Mexico Institute of Mining and Technology',
    'NOAO USA',
    'Northwestern University',
    'NRAO',
    'NRAO Charlottesville',
    'NRAO, Charlottesville',
    'NRC',
    'National Radio Astronomy Observatory',
    'National Radio Astronomy Observatory/University of Virginia',
    'NJIT',
    'OVRO',
    'Penn State',
    'Penn State University',
    'Princeton',
    'Princeton University',
    'Purdue University',
    'PUC',
    'Rutgers',
    'Rutgers University',
    'SAO CfA/Taiwan University',
    'SAO CfA/ASIAA',
    'SAO CfA',
    'SETI',
    'SLAC',
    'SMA',
    'SOFIA/USRA',
    'Space Telescope Science Institute',
    'SSC',
    'Stanford',
    'Stanford University',
    'Stony Brook University',
    'Stony Brook Univ.',
    'Stony Brook Univ',
    'Texas A\&M',
    'Tufts University',
    'UC Berkeley',
    'UC - Berkeley, MPE Garching',
    'UC Davis',
    'UC Irvine',
    'UC Santa Cruz',
    'U of Wisconsin',
    'UArizona',
    'U Arizona',
    'UAH',
    'UChicago',
    'UCLA',
    'UFlorida',
    'U Florida',
    'UH IfA',
    'UIUC',
    'UMASS',
    'UMass',
    'UMD',
    'UMD/PUC',
    'UMichigan Ann Arbor, Observatorio Nacional Brazil',
    'UMissouri-Kansas City',
    'University of Alabama, Huntsville',
    'University of Arizona',
    'University of California, Los Angeles',
    'University of Colorado',
    'University of Florida',
    'University of Hawaii',
    'University of Iowa',
    'University of Massachusetts',
    'University of Michigan',
    'University of Minnesota',
    'University of Missouri',
    'University of Pennsylvania',
    'University of Rochester',
    'University of Texas',
    'University of Texas at Austin',
    'University of Toledo',
    'Univ. of Toledo, USA',
    'University of Virginia',
    'University of Wisconsin',
    'Univ. of Minnesota',
    'Univ. of Washington',
    'Univ. of Wisconsin Milwaukee',
    'UPenn',
    'USRA - SOFIA',
    'UT Austin',
    'UvA',
    'UVa',
    'West Virginia University',
    'Williams College',
    'Yale',
]

def isus(inst):
    if inst in US_inst:
        return '1'
    elif inst in NUS_inst:
        return '0'
    else:
        print inst
        return 'N/A'

